### ISSUE TITLE
允许串口关闭时添加或删除变量

### ISSUE THREAD

**Issue by M3chD09** [scutrobotlab/asuwave#4]
在串口关闭的情况下删除观察变量，上位机不会发送删除观察变量的指令到单片机，要在串口打开的时候删除才行

**Comment by BigeYoung** [comment]
解决

**Comment by BigeYoung** [comment]
@M3chD09 觉得 删除观察变量仅在串口开启时有效 应该是即使串口关闭也能删除变量，而不是做个校验没有串口的时候不能删

**Comment by BigeYoung** [comment]
初步研究认为，是chart的相关代码只负责添加不负责删除所致。https://github.com/scutrobotlab/asuwave/blob/main/src/components/ChartCard.vue#L132-L132
